/**
 * fetch-fonts.mts — download the two display faces the UI bundles, and write the @font-face CSS
 * that loads them.
 *
 *   npx tsx scripts/fetch-fonts.mts
 *
 * WHY BUNDLED, NOT LINKED. The renderer's CSP is `font-src 'self' data:` (index.html) and the app
 * makes no network calls it did not list in src/main/security.ts; a `<link>` to Google Fonts
 * would be blocked by the first and a leak by the second. So the files are fetched ONCE, here,
 * committed under src/renderer/src/assets/fonts/, and served from the bundle like any asset.
 *
 * WHAT. Orbitron (headings, nav, buttons — the geometric retro-wave display face) and Share Tech
 * Mono (the "console readout" numerals). Both are SIL Open Font License 1.1; NOTICE carries the
 * attribution. Only the `latin` subset of each is taken: the UI is English and the item/mob
 * names that carry accents render in the body face, not these.
 *
 * Google's CSS endpoint returns woff2 (with `unicode-range` split by subset) only when asked with
 * a modern browser UA — the default `fetch` UA gets TTF for everything. Hence the UA below.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'src', 'renderer', 'src', 'assets', 'fonts')
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

interface Face {
  family: string
  /** the css2 `family=` query */
  query: string
  weights: number[]
}
const FACES: Face[] = [
  { family: 'Orbitron', query: 'Orbitron:wght@500;700', weights: [500, 700] },
  { family: 'Share Tech Mono', query: 'Share+Tech+Mono', weights: [400] }
]

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${url}: ${String(res.status)}`)
  return res.text()
}
async function fetchBytes(url: string): Promise<Uint8Array> {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${url}: ${String(res.status)}`)
  return new Uint8Array(await res.arrayBuffer())
}

/** One `@font-face { … }` block of Google's stylesheet, as the fields this script needs. */
interface Block {
  subset: string
  weight: number
  url: string
}
function parseBlocks(css: string): Block[] {
  const out: Block[] = []
  const re = /\/\* (\w[\w-]*) \*\/\s*@font-face \{([^}]*)\}/g
  for (const m of css.matchAll(re)) {
    const body = m[2]
    const weight = /font-weight:\s*(\d+)/.exec(body)
    const url = /url\((https:[^)]+\.woff2)\)/.exec(body)
    if (weight && url) out.push({ subset: m[1], weight: Number(weight[1]), url: url[1] })
  }
  return out
}

async function main(): Promise<void> {
  mkdirSync(OUT, { recursive: true })
  const css: string[] = [
    '/* GENERATED by scripts/fetch-fonts.mts — do not edit; re-run the script to change faces. */',
    '/* Orbitron and Share Tech Mono, SIL Open Font License 1.1 (see NOTICE). Latin subset only. */',
    ''
  ]
  for (const face of FACES) {
    const sheet = await fetchText(`https://fonts.googleapis.com/css2?family=${face.query}&display=swap`)
    const blocks = parseBlocks(sheet).filter((b) => b.subset === 'latin' && face.weights.includes(b.weight))
    if (blocks.length !== face.weights.length) {
      throw new Error(`${face.family}: expected ${String(face.weights.length)} latin faces, parsed ${String(blocks.length)}`)
    }
    for (const b of blocks) {
      const file = `${face.family.replace(/\s+/g, '')}-${String(b.weight)}.woff2`
      const bytes = await fetchBytes(b.url)
      writeFileSync(join(OUT, file), bytes)
      console.log(`${file}  ${String(bytes.length)} bytes`)
      css.push(
        '@font-face {',
        `  font-family: '${face.family}';`,
        '  font-style: normal;',
        `  font-weight: ${String(b.weight)};`,
        '  font-display: swap;',
        `  src: url('./${file}') format('woff2');`,
        '}',
        ''
      )
    }
  }
  writeFileSync(join(OUT, 'fonts.css'), css.join('\n'))
  console.log(`wrote ${join('src/renderer/src/assets/fonts', 'fonts.css')}`)
}

await main()
