/**
 * refreshDiff.mts — the PURE diff behind `npm run refresh:data` (scripts/refresh-data.mts).
 *
 * No I/O, no network, no process: it takes two parsed snapshots of a scraped data file and
 * says what moved. Kept separate from the runner for the usual reason this repo splits pure
 * cores out of scripts — the interesting logic is then testable by `node --test` in
 * milliseconds (tests/refreshDiff.test.mts) instead of behind a 15-minute crawl.
 *
 * TWO SHAPES, ONE ANSWER. The three wiki scrapers write two different containers:
 *   * `src/main/data/items.json` is `{ scrapedAt, source, count, items: Record<key, entry> }`
 *     — a KEYED MAP, so `diffKeyed` walks the keys (the runner hands it `file.items`, which
 *     is what makes the report name actual items rather than the four top-level fields).
 *   * `mobs.json` / `quests.json` are `{ scrapedAt, source, mobs|quests: Entry[] }`, sorted by
 *     wiki page title — `diffByPage` re-keys the array by `page` and reuses the same walk.
 * Both return the same `DataDiff`, so the formatter and the runner never branch on source.
 *
 * DEEP EQUALITY IS `JSON.stringify`. That is exact here rather than approximate: every one of
 * these files is GENERATED by a scraper that builds each entry field-by-field in a fixed order
 * and sorts the container, so two runs that agree produce byte-identical entries. There is no
 * hand-edited JSON in this path whose key order could drift.
 *
 * THE STAMP. Every scraper stamps `scrapedAt` unconditionally, so a re-scrape that learned
 * nothing still rewrites the file and dirties `git status`. `stampOnly` is how the runner
 * detects that case (and then restores the previous bytes, the rule scrape-classes.ts already
 * follows for its own output). It means: everything compared is identical, so the only thing
 * that CAN differ is an ignored key — the stamp. A first-ever scrape (`prev === null`) is
 * never stamp-only; it is entirely `added`.
 */

/** What changed between two snapshots of one scraped file. */
export interface DataDiff {
  /** keys (item keys, or wiki page titles) present only in the new snapshot, sorted */
  added: string[]
  /** keys present only in the previous snapshot, sorted */
  removed: string[]
  /** keys present in both whose entry is not deep-equal, sorted */
  changed: string[]
  /** how many keys are present in both and identical */
  unchanged: number
  /** nothing but the (ignored) `scrapedAt` stamp can differ — see the header */
  stampOnly: boolean
}

/** How many drop edges (mob page + item name) the mob catalog gained and lost. */
export interface DropEdgeDelta {
  added: number
  removed: number
}

/** The only thing `dropEdgeDelta` needs of a mob record. `MobEntry.drops` is item NAMES. */
export interface DropSource {
  page: string
  drops?: readonly string[]
}

/** Keys skipped by default: the stamp, which is the whole reason this module exists. */
const DEFAULT_IGNORE_KEYS = ['scrapedAt']

/** Deep-equality handle for one entry. See "DEEP EQUALITY" in the header. */
const encode = (v: unknown): string => JSON.stringify(v) ?? 'undefined'

/** Finish a diff: `stampOnly` is derived, never passed in, so it cannot disagree with the buckets. */
function sealed(d: Omit<DataDiff, 'stampOnly'>, hadPrev: boolean): DataDiff {
  const same = d.added.length === 0 && d.removed.length === 0 && d.changed.length === 0
  return { ...d, stampOnly: hadPrev && same }
}

/**
 * Diff two keyed records. `ignoreKeys` (default `['scrapedAt']`) drops keys from BOTH sides
 * before comparing, so a whole file object can be passed as-is when that is what a caller
 * has; the runner passes the inner `items` map, where the default matches nothing.
 *
 * `prev === null` (no previous file on disk) means every key is `added`.
 */
export function diffKeyed(
  prev: Record<string, unknown> | null,
  next: Record<string, unknown>,
  opts?: { ignoreKeys?: string[] }
): DataDiff {
  const ignore = new Set(opts?.ignoreKeys ?? DEFAULT_IGNORE_KEYS)
  const nextKeys = Object.keys(next).filter((k) => !ignore.has(k))
  if (prev === null) {
    return sealed({ added: [...nextKeys].sort(), removed: [], changed: [], unchanged: 0 }, false)
  }
  const prevKeys = Object.keys(prev).filter((k) => !ignore.has(k))
  const prevSet = new Set(prevKeys)
  const nextSet = new Set(nextKeys)
  const added: string[] = []
  const changed: string[] = []
  let unchanged = 0
  for (const k of nextKeys) {
    if (!prevSet.has(k)) added.push(k)
    else if (encode(prev[k]) === encode(next[k])) unchanged++
    else changed.push(k)
  }
  const removed = prevKeys.filter((k) => !nextSet.has(k))
  return sealed(
    { added: added.sort(), removed: removed.sort(), changed: changed.sort(), unchanged },
    true
  )
}

/** Re-key an entry array by its wiki page title. Later rows win; the scrapers emit no dupes. */
function byPage(rows: readonly { page: string }[]): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const row of rows) out[row.page] = row
  return out
}

/**
 * Diff two page-keyed entry ARRAYS (mobs.json, quests.json). `ignoreKeys` is deliberately
 * EMPTY here: the keys are wiki page titles, and a page may legitimately be called anything.
 */
export function diffByPage<T extends { page: string }>(
  prev: readonly T[] | null,
  next: readonly T[]
): DataDiff {
  return diffKeyed(prev === null ? null : byPage(prev), byPage(next), { ignoreKeys: [] })
}

/** The same object minus its `scrapedAt` stamp — the payload, which is what a diff is about. */
export function stripStamp<T extends { scrapedAt?: string }>(v: T): T {
  const { scrapedAt: _scrapedAt, ...rest } = v
  return rest as T
}

/** Every (page, item) pair the catalog states, as unambiguous keys. */
function dropEdges(mobs: readonly DropSource[]): Set<string> {
  const edges = new Set<string>()
  for (const mob of mobs) {
    for (const item of mob.drops ?? []) edges.add(JSON.stringify([mob.page, item]))
  }
  return edges
}

/**
 * How many mob-to-item DROP EDGES appeared and disappeared. This is the number ROADMAP §2 asks
 * `refresh:data` to print: "12 mobs changed" says nothing about whether the loot tables the
 * Zone loot view reads actually moved, and this does.
 */
export function dropEdgeDelta(
  prev: readonly DropSource[] | null,
  next: readonly DropSource[]
): DropEdgeDelta {
  const after = dropEdges(next)
  if (prev === null) return { added: after.size, removed: 0 }
  const before = dropEdges(prev)
  let added = 0
  for (const e of after) if (!before.has(e)) added++
  let removed = 0
  for (const e of before) if (!after.has(e)) removed++
  return { added, removed }
}

/** One bucket's lines: at most `cap` names, then how many were elided. */
function bucketLines(sign: string, names: readonly string[], cap: number): string[] {
  const lines = names.slice(0, cap).map((n) => `  ${sign} ${n}`)
  if (names.length > cap) lines.push(`    +${names.length - cap} more`)
  return lines
}

/**
 * Render one source's diff for the console. A stamp-only run collapses to a SINGLE line —
 * the whole point of a release-time refresh is that most sources say "nothing moved", and
 * three paragraphs of zeroes would bury the one source that did.
 */
export function formatDiff(label: string, d: DataDiff, cap = 10): string {
  if (d.stampOnly) return `${label}: unchanged (${d.unchanged} entries, payload identical)`
  const lines = [
    `${label}: ${d.added.length} added, ${d.removed.length} removed, ` +
      `${d.changed.length} changed, ${d.unchanged} unchanged`
  ]
  const buckets: [string, string[]][] = [
    ['+', d.added],
    ['-', d.removed],
    ['~', d.changed]
  ]
  for (const [sign, names] of buckets) lines.push(...bucketLines(sign, names, cap))
  return lines.join('\n')
}
