// Build the WordPress.com deliverables from the source files in this folder.
//   node build.mjs
// Outputs: wordpress.css (sanitizer-safe), <page>-blocks.html, preview.html, payload.json
// (what a wp-admin tab fetches and pushes through wp.apiFetch; see README.md).
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
const here = path.dirname(fileURLToPath(import.meta.url))
const read = (f) => fs.readFileSync(path.join(here, f), 'utf8')
const write = (f, s) => { fs.mkdirSync(path.dirname(path.join(here, f)), { recursive: true }); fs.writeFileSync(path.join(here, f), s) }

// WordPress.com strips CSS custom properties, @import and backdrop-filter. Inline the variables
// and carry the fonts as @font-face blocks (fonts.css is the latin subset of the Google Fonts CSS).
const src = read('additional.css')
const vars = {}
let css = src.replace(/^\s*--([\w-]+):(.*);\s*$/mg, (m, k, v) => { vars[k] = v.trim(); return '' })
css = css.replace(/var\(--([\w-]+)\)/g, (m, k) => { if (!(k in vars)) throw new Error('unknown var ' + k); return vars[k] })
css = css.replace(/^@import[^\n]*\n/m, '').replace(/\/\* =+[\s\S]*?=+ \*\/\n/, '').replace(/\n{3,}/g, '\n\n')
const wpcss = '/* EQ Zera (eqzera.com). Generated by website/build.mjs from additional.css: literal colours and @font-face blocks because WordPress.com strips custom properties and @import. Do not edit here. */\n' + read('fonts.css') + '\n' + css
write('wordpress.css', wpcss)

const pages = {}
for (const f of fs.readdirSync(here).filter((f) => f.endsWith('-body.html'))) {
  const slug = f.replace(/-body\.html$/, '')
  pages[slug] = '<!-- wp:html -->\n' + read(f) + '<!-- /wp:html -->\n'
  write(slug + '-blocks.html', pages[slug])
}
const previewCss = src.replace(/^@import[^\n]*\n/m, '')
write('preview.html', '<title>EQ Zera</title>\n<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@500;700&family=Source+Sans+3:ital,wght@0,400;0,600;1,400&family=JetBrains+Mono:wght@400;600&display=swap">\n<style>\nhtml,body{background:#0c0a1f;margin:0}\n' + previewCss + '</style>\n' + read('home-body.html'))
write('payload.json', JSON.stringify({ css: wpcss, pages }))
console.log('built', Object.keys(pages).join(', '), '| css', wpcss.length, 'bytes')
